name: just_animations
description: A package to make it easy to animate widgets and customizing them with different features.
version: 0.0.1
homepage: https://github.com/DamianAldair/just_animations
repository: https://github.com/DamianAldair/just_animations

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
